[resources.skills.osx-commit]
version = "0.1.0"

[resources.skills.osx-concepts]
version = "0.7.0"

[resources.skills.osx-workflow]
version = "0.2.0"

[resources.skills.osx-generate-changelog]
version = "0.2.1"

[resources.skills.osx-maintain-ai-docs]
version = "0.2.0"

[resources.skills.osx-modify-artifacts]
version = "0.2.3"

[resources.skills.osx-review-artifacts]
version = "0.2.6"

[resources.skills.osx-review-test-compliance]
version = "0.2.0"

[resources.commands.osx-changelog]
version = "0.2.0"

[resources.commands.osx-maintain-docs]
version = "0.2.0"

[resources.commands.osx-modify]
version = "0.2.0"

[resources.commands.osx-review]
version = "0.2.0"

[resources.commands.osx-verify-tests]
version = "0.2.0"
